app <- ShinyDriver$new("../")
app$snapshotInit("test_21052020_world")

app$setInputs(`world-c1` = "ac")
app$snapshot()
app$setInputs(`world-c1` = "d")
app$snapshot()
app$setInputs(`world-c1` = "r")
app$snapshot()
app$setInputs(`world-c1` = "ncc")
app$snapshot()
app$setInputs(`world-c1` = "nac")
app$snapshot()
app$setInputs(`world-c1` = "nd")
app$snapshot()
app$setInputs(`world-c1` = "nr")
app$snapshot()
app$setInputs(`world-c1` = "cc")
app$snapshot()
